# generated by datamodel-codegen:
#   filename:  aws_s3.yml
#   timestamp: 2022-10-07T18:59:56+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class S3Type(Enum):
    Private = 'Private'
    Public = 'Public'


class RegionEndpoint(Enum):
    us_east_1 = 'us-east-1'
    sa_east_1 = 'sa-east-1'


class S3(BaseModel):
    account: Optional[str] = None
    name_bucket: Optional[str] = Field(None, description='Name of bucker')
    id: Optional[str] = Field(None, description='Id account')
    s3_type: Optional[S3Type] = Field(None, description='Private or public')
    region_endpoint: Optional[RegionEndpoint] = Field(
        None, description='Region end point'
    )
