# generated by datamodel-codegen:
#   filename:  aws_s3.yml
#   timestamp: 2022-10-07T13:14:56+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field



import streamlit as st
import streamlit_pydantic as sp

# class S3Type(Enum):
#     Private = 'Private'
#     Public = 'Public'


# class S3(BaseModel):
#     account: Optional[str] = None
#     name_bucket: Optional[str] = Field(None, description='Name of bucker')
#     id: Optional[str] = Field(None, description='Id account')
#     s3_type: Optional[S3Type] = Field(None, description='Private or public')
#     region_endpoint: Optional[str] = Field(None, description='Region end point')




class Pet(BaseModel):
    id: int
    name: str
    tag: Optional[str] = None


class Pets(BaseModel):
    __root__: List[Pet]


class Error(BaseModel):
    code: int
    message: str


class Api(BaseModel):
    apiKey: Optional[str] = Field(
        None, description='To be used as a dataset parameter value'
    )
    apiVersionNumber: Optional[str] = Field(
        None, description='To be used as a version parameter value'
    )
    apiUrl: Optional[str] = Field(
        None, description="The URL describing the dataset's fields"
    )
    apiDocumentationUrl: Optional[str] = Field(
        None, description='A URL to the API console for each API'
    )


class Apis(BaseModel):
    __root__: List[Api]

with st.form(key="form"):

    data_form = sp.pydantic_input(key="dara",model=Apis)

    submit = st.form_submit_button()
