# generated by datamodel-codegen:
#   filename:  https://json.schemastore.org/codeclimate.json
#   timestamp: 2022-10-10T00:39:01+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field

import streamlit as st
import streamlit_pydantic as sp


class Enabled1(BaseModel):
    title: str
    type: str
    default: bool


class Properties(BaseModel):
    enabled: Enabled1


class Enabled(BaseModel):
    type: str
    properties: Properties


class Config(BaseModel):
    title: str
    type: str


class Threshold(BaseModel):
    title: str
    type: List[str]


class Definitions(BaseModel):
    enabled: Enabled
    config: Config
    threshold: Threshold


class Version(BaseModel):
    title: str
    description: str
    type: str
    default: str


class Url(BaseModel):
    title: str
    type: str
    format: str


class Path(BaseModel):
    title: str
    type: str


class Properties2(BaseModel):
    url: Url
    path: Path


class Items(BaseModel):
    type: str
    properties: Properties2


class Prepare(BaseModel):
    title: str
    type: str
    items: Items


class Threshold1(BaseModel):
    _ref: str = Field(..., alias='$ref')
    default: int


class Properties5(BaseModel):
    threshold: Threshold1


class Config1(BaseModel):
    _ref: str = Field(..., alias='$ref')
    properties: Properties5


class Properties4(BaseModel):
    config: Config1


class ArgumentCount(BaseModel):
    title: str
    _ref: str = Field(..., alias='$ref')
    properties: Properties4


class Threshold2(BaseModel):
    _ref: str = Field(..., alias='$ref')
    default: int


class Properties7(BaseModel):
    threshold: Threshold2


class Config2(BaseModel):
    _ref: str = Field(..., alias='$ref')
    properties: Properties7


class Properties6(BaseModel):
    config: Config2


class ComplexLogic(BaseModel):
    title: str
    _ref: str = Field(..., alias='$ref')
    properties: Properties6


class Threshold3(BaseModel):
    _ref: str = Field(..., alias='$ref')
    default: int


class Properties9(BaseModel):
    threshold: Threshold3


class Config3(BaseModel):
    _ref: str = Field(..., alias='$ref')
    properties: Properties9


class Properties8(BaseModel):
    config: Config3


class FileLines(BaseModel):
    title: str
    _ref: str = Field(..., alias='$ref')
    properties: Properties8


class Threshold4(BaseModel):
    _ref: str = Field(..., alias='$ref')
    default: int


class Properties11(BaseModel):
    threshold: Threshold4


class Config4(BaseModel):
    _ref: str = Field(..., alias='$ref')
    properties: Properties11


class Properties10(BaseModel):
    config: Config4


class MethodComplexity(BaseModel):
    title: str
    _ref: str = Field(..., alias='$ref')
    properties: Properties10


class Threshold5(BaseModel):
    _ref: str = Field(..., alias='$ref')
    default: int


class Properties13(BaseModel):
    threshold: Threshold5


class Config5(BaseModel):
    _ref: str = Field(..., alias='$ref')
    properties: Properties13


class Properties12(BaseModel):
    config: Config5


class MethodCount(BaseModel):
    title: str
    _ref: str = Field(..., alias='$ref')
    properties: Properties12


class Threshold6(BaseModel):
    _ref: str = Field(..., alias='$ref')
    default: int


class Properties15(BaseModel):
    threshold: Threshold6


class Config6(BaseModel):
    _ref: str = Field(..., alias='$ref')
    properties: Properties15


class Properties14(BaseModel):
    config: Config6


class MethodLines(BaseModel):
    title: str
    _ref: str = Field(..., alias='$ref')
    properties: Properties14


class Threshold7(BaseModel):
    _ref: str = Field(..., alias='$ref')
    default: int


class Properties17(BaseModel):
    threshold: Threshold7


class Config7(BaseModel):
    _ref: str = Field(..., alias='$ref')
    properties: Properties17


class Properties16(BaseModel):
    config: Config7


class NestedControlFlow(BaseModel):
    title: str
    _ref: str = Field(..., alias='$ref')
    properties: Properties16


class Threshold8(BaseModel):
    _ref: str = Field(..., alias='$ref')
    default: int


class Properties19(BaseModel):
    threshold: Threshold8


class Config8(BaseModel):
    _ref: str = Field(..., alias='$ref')
    properties: Properties19


class Properties18(BaseModel):
    config: Config8


class ReturnStatements(BaseModel):
    title: str
    _ref: str = Field(..., alias='$ref')
    properties: Properties18


class Threshold9(BaseModel):
    _ref: str = Field(..., alias='$ref')


class Properties21(BaseModel):
    threshold: Threshold9


class Config9(BaseModel):
    _ref: str = Field(..., alias='$ref')
    properties: Properties21


class Properties20(BaseModel):
    config: Config9


class SimilarCode(BaseModel):
    title: str
    _ref: str = Field(..., alias='$ref')
    properties: Properties20


class Threshold10(BaseModel):
    _ref: str = Field(..., alias='$ref')


class Properties23(BaseModel):
    threshold: Threshold10


class Config10(BaseModel):
    _ref: str = Field(..., alias='$ref')
    properties: Properties23


class Properties22(BaseModel):
    config: Config10


class IdenticalCode(BaseModel):
    title: str
    _ref: str = Field(..., alias='$ref')
    properties: Properties22


class Properties3(BaseModel):
    argument_count: ArgumentCount = Field(..., alias='argument-count')
    complex_logic: ComplexLogic = Field(..., alias='complex-logic')
    file_lines: FileLines = Field(..., alias='file-lines')
    method_complexity: MethodComplexity = Field(..., alias='method-complexity')
    method_count: MethodCount = Field(..., alias='method-count')
    method_lines: MethodLines = Field(..., alias='method-lines')
    nested_control_flow: NestedControlFlow = Field(..., alias='nested-control-flow')
    return_statements: ReturnStatements = Field(..., alias='return-statements')
    similar_code: SimilarCode = Field(..., alias='similar-code')
    identical_code: IdenticalCode = Field(..., alias='identical-code')


class Checks(BaseModel):
    title: str
    type: str
    properties: Properties3


class AdditionalProperties(BaseModel):
    _ref: str = Field(..., alias='$ref')


class Plugins(BaseModel):
    title: str
    description: str
    type: str
    additionalProperties: AdditionalProperties


class Items1(BaseModel):
    title: str
    type: str


class ExcludePatterns(BaseModel):
    title: str
    type: str
    items: Items1


class Properties1(BaseModel):
    version: Version
    prepare: Prepare
    checks: Checks
    plugins: Plugins
    exclude_patterns: ExcludePatterns


class Model(BaseModel):
    _comment: str = Field(..., alias='$comment')
    _schema: str = Field(..., alias='$schema')
    definitions: Definitions
    description: str
    properties: Properties1
    title: str
    type: str


with st.form(key="form-data "):

    data_form = sp.pydantic_input(key="data",model=Model)

    submit = st.form_submit_button()