# generated by datamodel-codegen:
#   filename:  2bb6fcf26b2e47ac8a2df448786ec616_s3.yml
#   timestamp: 2023-03-23T20:53:58+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, constr


class S3Type(Enum):
    Private = 'Private'
    Public = 'Public'


class RegionEndpoint(Enum):
    us_east_1 = 'us-east-1'
    sa_east_1 = 'sa-east-1'


class S3(BaseModel):
    name_bucket: Optional[constr(min_length=2, max_length=15)] = Field(
        None, description='Name of bucker'
    )
    id: Optional[str] = Field(None, description='Id account')
    s3_type: Optional[S3Type] = Field(None, description='Private or public')
    region_endpoint: Optional[RegionEndpoint] = Field(
        None, description='Region end point'
    )
    server_side_encrypt: Optional[bool] = Field(None, description='Region end point')
