name: Build and Push Docker Image (Test)

on:
  workflow_dispatch: # Permite executar manualmente o workflow no GitHub Actions

jobs:
  setting-environment:
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.set-branch.outputs.branch }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Definir nome da branch de origem como variável (sem "/")
        id: set-branch
        run: |
          BRANCH_NAME=$(echo '${{ github.ref_name }}' | tr '/' '-')
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

  build:
    needs: setting-environment
    runs-on: ubuntu-latest
    outputs:
      build-success: ${{ steps.build.outcome == 'success' }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build da imagem Docker
        id: build
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ needs.setting-environment.outputs.branch-name }} .

  sonar-code-analysis:
    needs: setting-environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Rodar SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=k-ops-sonar-yaml \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=$SONAR_TOKEN

  image-analyzer:
    needs: [build, sonar-code-analysis]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Simular análise de imagem
        run: |
          echo "Analisando imagem gerada..."
          # Substitua por uma ferramenta de análise de segurança, como Trivy

  push:
    needs: [build, image-analyzer]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push da imagem para GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ needs.build.outputs.branch-name }}